# -*- coding: utf-8 -*-
"""國立臺北科技大學_金融大數據_作業4_關聯分析(20230519).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_aSJwYOimfGSOMaHCKm5F4CT_Jvq8BGd
"""

import pandas as pd
import numpy as np
import string as st

# pd.set_option('display.max_columns',500)
# pd.set_option('display.max_rows',200)
df = pd.read_csv("gamestudy.csv", encoding = 'ISO-8859-1')
df

df.drop(['S. No.' , 'Timestamp'] , axis = 1 , inplace = True)

df.isnull().sum()

df.shape

df['Hours_streams'] = df['Hours'] + df['streams']
df['Hours_streams']

df[df['Hours_streams'] > 115].index

df[df['Hours_streams']==0].index

(df[df['Hours_streams'] > 115].index) | (df[df['Hours_streams']==0].index)

df.drop(  ((df[df['Hours_streams'] > 115].index) | (df[df['Hours_streams']==0].index)),axis=0,inplace=True)

# df['Hours_streams'].value_counts()

df.GADE.value_counts()

df.GADE.fillna(df.GADE.value_counts().index[1] , inplace=True) #1

df.streams.fillna(int(df.streams.mean()) , inplace = True)

df.Hours.fillna(int(df.Hours.mean()) , inplace = True)

df.drop('Hours_streams' , axis = 1 , inplace = True)

df.League = df.League.str.lower().str.strip()
print(df.League.nunique())

df["League"] =df["League"].str.extract(r'^([a-z]+)')

df.League.unique()

df.loc[(df['whyplay']== 'having fun') ,'League'] = df.loc[(df['whyplay']== 'having fun') ,'League'].fillna('unranked')
df.League.fillna('gold' , inplace = True)

golds = ['g', 'gv', 'golden' ,'glod' ,'golld' ,'golf', 'goled', 'golderino' ,'giii']
df['League'] = df.League.replace(golds , 'gold')

silvers = [ 'silverii' , 's' , 'sliver' , 'siver' , 'silber' , 'sil' , 'silveriv']
df['League'] = df.League.replace(silvers , 'silver')

plats = [
    'platinium' , 'platnium' , 'platin' ,'pplatinum' ,'plarinum' ,'platium', 'p' ,'platine' ,
    'platinun' ,'platonum' ,'platnum', 'plata' ,'plantinum',
    'platinuim' ,'platunum', 'plantinum' ,'platunum' ,'platinumm' ,'platv' ,'platina' , 'plat' 
]
df['League'] = df.League.replace(plats , 'platinum')

bronzers = ['bronce' , 'b' , 'broze' ,'lowest' , 'wood', 'elohell'] 
df['League'] = df.League.replace(bronzers , 'bronze')

unranked = ['none' ,'na', 'not' ,'n' ,'promos' ,'provisional' ,'placements' , 'dont' , 'was', 'unraked',
            'havent', 'never', 'nope', 'no', 'noone', 'don', 'of', 'unrranked', 'new', 'what', 'unrank' ,
            'ranked', 'placement', 'unrankt' , 'non', 'unfranked' , 'promotion', 'idk',
            'unplaced', 'probably', 'provisionals', 'didnt' ,'unrakned' , 'unfinished' , 'just' , 'x' ,
            'promotions' , 'unseeded' , 'haven']
df['League'] = df.League.replace(unranked , 'unranked')

diamonds =  ['d', 'dia', 'diaomnd', 'diamont','diamomd']
df['League'] = df.League.replace(diamonds , 'diamond')

gm =  ['grand', 'gm', 'grandmasters']
df['League'] = df.League.replace(gm , 'grandmaster')

chall =  ['challenjour', 'c', 'charrenjour', 'challeneger']
df['League'] = df.League.replace(chall , 'challenger')

df['League'] = df.League.replace('mg' , 'mge')
df['League'] = df.League.replace('masters' , 'master')
df['League'] = df.League.replace( ['le', 'legdendary'] , 'legendary')

counts = df['League'].value_counts()
df['League'] = df['League'][~df['League'].isin(counts[counts < 3].index)]

df['League'] = df.League.replace(['i' , 'currently' , 'high' , 'season' , 'lol','cs' ,
                                  'last' ,'csgo','starcraft' ,'geater' , 'in', 'rank' , 'still'] , np.nan)

df.League.fillna('unspecified' , inplace=True)

df.League.value_counts()

df.drop(["Birthplace","Birthplace_ISO3"],axis=1,inplace=True)

df['Residence'] = df['Residence'].replace('Unknown',df['Residence'].mode()[0])

df['Reference'].fillna('Other',inplace=True)

df.drop(df[df['accept'].isnull()].index , axis=0 , inplace=True)

df['Residence_ISO3'].fillna('USA',inplace=True) #11063

df.loc[11063,'Residence_ISO3'] = 'XXK'

col = ['SPIN1','SPIN2','SPIN3','SPIN4','SPIN5','SPIN6','SPIN7','SPIN8','SPIN9',
     'SPIN10','SPIN11','SPIN12','SPIN13','SPIN14','SPIN15','SPIN16','SPIN17' ,'SPIN_T']
for i in col :
    df[i].fillna(df[i].mode()[0], inplace = True)

df['Playstyle'] = df['Playstyle'].apply(lambda x: ' '.join(word.strip(st.punctuation) for word in x.split()))
df['earnings'] = df['earnings'].apply(lambda x: ' '.join(word.strip(st.punctuation) for word in x.split()))
df['whyplay'] = df['whyplay'].apply(lambda x: ' '.join(word.strip(st.punctuation) for word in x.split()))

df['Playstyle'] = df['Playstyle'].str.lower().str.strip()
df['whyplay'] = df['whyplay'].str.lower().str.strip()
df['earnings'] = df['earnings'].str.lower().str.strip()

df['Playstyle'].nunique()

df.drop('highestleague' , axis = 1 , inplace = True)

df.Work.fillna(df.Work.mode()[0] , inplace=True)

df.drop(['Residence' , 'accept'] , axis = 1 , inplace = True)

df.earnings.replace(df.earnings.value_counts().index[3:] , 'Other',inplace=True)
df['earnings'].value_counts()

df.whyplay.replace(df.whyplay.value_counts().index[5:] , 'Other',inplace=True)
df['whyplay'].value_counts()

df.Playstyle.replace(df.Playstyle.value_counts().index[5:] , 'Other',inplace=True)
df['Playstyle'].value_counts()

df.Playstyle.replace('Other' , np.nan , inplace=True)
df.whyplay.replace('Other' , np.nan , inplace=True)
df.earnings.replace('Other' , np.nan , inplace=True)

df.dropna(inplace=True)

df.isnull().sum()

df.shape

df.to_csv('gamestudy.csv')

