# -*- coding: utf-8 -*-
"""國立臺北科技大學_金融大數據_作業3_SalaryClassification(20230505).ipynb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/182qSZz-nYh_cGV1CjY0MYRJHaWvLctpg
"""

# import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('salary.csv')
df.shape
if df.shape[0] != 32561: raise Exception('資料筆數錯誤')

# some statistical values in numeric features
df.describe()

# df.iloc[5361]

# TODO: 查看是否有缺失值
# df['workclass'].value_counts()[' ?'] #Example
for column_name in df.columns: 
  if ' ?' in df[str(column_name)].value_counts():
    print(column_name, "(", df[str(column_name)].value_counts()[' ?'], "筆)")

df['workclass'].value_counts()

pd.DataFrame(df['workclass'].value_counts())

df['occupation'].value_counts()

pd.DataFrame(df['occupation'][df['workclass']==' Private'].value_counts())

pd.DataFrame(df['native-country'].value_counts())

df['workclass'].replace(' ?', np.nan, inplace=True)

df[df['workclass'].isnull()]

df['native-country'].replace(' ?', np.nan, inplace=True)

df.isnull().sum()

df['workclass'].fillna(df['workclass'].mode()[0], inplace=True)
df['workclass'].isnull().sum()

sum = 0
for num_iloc in range(len(df)):
  if df['workclass'].iloc[num_iloc]==' Private' and df['occupation'].iloc[num_iloc] == ' ?':
    df['occupation'].iloc[num_iloc] = 'Craft-repair'
    sum += 1
print(sum)

df['occupation'].value_counts()

df['occupation'].replace(' ?', np.nan, inplace=True)

df['occupation'].fillna('No Occupation', inplace=True)
df['occupation'].isnull().sum()

df['native-country'].fillna(df['native-country'].mode()[0], inplace=True)
df['native-country'].isnull().sum()

df['native-country'].value_counts()

"""# Draft 草稿區 #"""

# df['occupation'][df['workclass']==' Private'].fillna('Craft-repair', inplace=True)
# df['occupation'][df['workclass']==' Private'].isnull().sum()

# sum = 0
# for num_iloc in range(len(df['occupation'][df['workclass']==' Private'])):
#   if df['occupation'][df['workclass']==' Private'].iloc[num_iloc] == ' ?':
#     df['occupation'][df['workclass']==' Private'].iloc[num_iloc] = 'Craft-repair'
#     sum += 1
# print(sum)

